language: php

dist: trusty

sudo: required

cache:
  directories:
    - $HOME/.composer/cache/files

php:
  - '7.1'

before_install:
  - mysql -e 'CREATE DATABASE tania_test'

install:
  - cp -a .env-example .env
  - composer install --no-interaction
  - php bin/console --no-interaction doctrine:migrations:migrate
  - php bin/console --no-interaction doctrine:fixtures:load

script:
  - ./vendor/bin/phpunit

after_success:
  - docker build -t tanibox/tania -f docker/app/Dockerfile --build-arg BUILD_DATE="$(date +%Y-%m-%d)" .
 
branches:
  only: 
    - development

services:
  - mysql
