version: '2.2'

services:
  app:
    image: taniabox/tania:latest
    environment:
      SYMFONY_ENV: prod
      SYMFONY_LOCALE: en
      SYMFONY_SECRET: ThisTokenIsNotSoSecretChangeIt
      SYMFONY_DB_HOST: ~
      SYMFONY_DB_PORT: ~
      SYMFONY_DB_NAME: ~
      SYMFONY_DB_USERNAME: ~
      SYMFONY_DB_PASSWORD: ~
      SYMFONY_MAILER_TRANSPORT: ~
      SYMFONY_MAILER_HOST: ~
      SYMFONY_MAILER_PORT: ~
      SYMFONY_MAILER_USERNAME: ~
      SYMFONY_MAILER_PASSWORD: ~

  nginx:
    image: taniabox/tania-nginx:latest
    depends_on:
      - app
